{{ if .Values.serviceAccounts }}
{{- range .Values.serviceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required "Service Account name is required." .name }}
  namespace: {{ .namespace }}
  labels: {{ include "service-accounts.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
---
{{ end -}}
{{ end -}}
